// threeFiber
export const SET_INITIAL_MAP = 'SET_INITIAL_MAP'
export const SET_ACTIVE_OPTION = 'SET_ACTIVE_OPTION'
export const SET_SELECTED_COLOR_OBJ = 'SET_SELECTED_COLOR_OBJ'
export const SET_NEW_MATERIAL_OPT = 'SET_NEW_MATERIAL_OPT'


